import { RoadCase, InAppNotification } from '@/types';

export const DEMO_CASES: RoadCase[] = [
  {
    id: 'KZ-DEMO-001',
    citizenId: 'citizen-demo-user',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1200&q=80',
    location: {
      latitude: 21.2514,
      longitude: 81.6296,
      formattedAddress: 'NH-30, Near Tatibandh Interchange, Raipur, Chhattisgarh 492099',
      locality: 'Tatibandh',
      district: 'Raipur',
      state: 'Chhattisgarh',
      roadName: 'National Highway 30 (NH-30)',
      roadPlaceId: 'ChIJ5b0S1vM3VToRzK_DemoRoad_01',
      roadCategory: 'national_highway',
    },
    hazardAnalysis: {
      hazardType: 'pothole',
      severity: 'high',
      confidence: 0.94,
      description: 'Severe deep asphalt pothole directly across active high-speed lane with sharp rim fracture, presenting immediate tire blowout and vehicle loss-of-control hazards.',
      requiresAttention: true,
      visibleRoadClues: ['Dual carriage asphalt road', 'Heavy vehicle tire marks', 'Highway lane marking'],
      additionalHazards: ['Secondary aggregate debris scattered on lane', 'Water retention vulnerability'],
    },
    accidentIntelligence: {
      totalFound: 7,
      highRelevanceCount: 3,
      summary: 'Public news archives report 3 high-relevance collision and rollover incidents on the NH-30 Tatibandh corridor within the last 18 months.',
      events: [
        {
          id: 'acc-demo-1',
          date: '2026-04-12',
          location: 'NH-30 Tatibandh Flyover vicinity, Raipur',
          eventType: 'collision',
          severity: 'serious',
          source: 'The Hitavada (Raipur Bureau)',
          url: 'https://example.com/news/nh30-tatibandh-collision',
          title: 'Two trucks collide near Tatibandh on NH-30 following sudden swerve to avoid road crater',
          snippet: 'Police reported three people injured when a container truck swerved abruptly to avoid an unrepaired depression on the main carriageway.',
          relevance: 'HIGH',
          relevanceReason: 'Direct match for road name NH-30 and Tatibandh locality with road defect causation mentioned.',
        },
        {
          id: 'acc-demo-2',
          date: '2025-11-28',
          location: 'NH-30 Raipur-Dhamtari stretch',
          eventType: 'overturning',
          severity: 'fatal',
          source: 'Dainik Bhaskar Digital',
          url: 'https://example.com/news/nh30-rollover-incident',
          title: 'Fatal SUV rollover on NH-30 bypass near Raipur industrial zone',
          snippet: 'A motorist succumbed to injuries after losing control during night driving over uneven fractured surface on NH-30.',
          relevance: 'HIGH',
          relevanceReason: 'Corridor matches NH-30 Raipur corridor with fatal severity rating.',
        },
        {
          id: 'acc-demo-3',
          date: '2025-08-04',
          location: 'Tatibandh Chowk approach, NH-30',
          eventType: 'vehicle_accident',
          severity: 'moderate',
          source: 'Times of India (Raipur)',
          url: 'https://example.com/news/tatibandh-chowk-traffic-accident',
          title: 'Peak hour multi-vehicle pile-up at Tatibandh bottleneck slows traffic for three hours',
          snippet: 'Damaged road surface caused sudden braking cascades leading to consecutive rear-end collisions.',
          relevance: 'HIGH',
          relevanceReason: 'Direct match for Tatibandh approach and damaged road conditions.',
        },
        {
          id: 'acc-demo-4',
          date: '2025-03-19',
          location: 'Raipur-Bhilai Road segment',
          eventType: 'crash',
          severity: 'minor',
          source: 'Patrika Raipur',
          url: 'https://example.com/news/raipur-bhilai-expressway-minor-crash',
          title: 'Minor collision near Raipur border during morning fog',
          snippet: 'Two light commercial vehicles suffered minor damage.',
          relevance: 'MEDIUM',
          relevanceReason: 'Nearby district corridor connecting Raipur highway network.',
        }
      ],
    },
    authorityRouting: {
      authorityId: 'auth-cg-nhai-raipur',
      authorityName: 'National Highways Authority of India (NHAI)',
      department: 'Ministry of Road Transport and Highways (MoRTH)',
      jurisdiction: 'National Highways Corridor (NH-30, NH-53, NH-130B) - Raipur Region',
      routingConfidence: 0.95,
      reason: 'Assigned because the identified road falls within the configured national highway jurisdiction for this corridor in Raipur district.',
      escalationAuthority: 'Regional Office NHAI, Chhattisgarh Zone',
      isDemo: true,
    },
    priorityAssessment: {
      priority: 'HIGH',
      factors: [
        'High-severity pothole detected on high-speed carriageway',
        'Multiple relevant historical accident reports found on NH-30 Tatibandh stretch',
        'Persistent crowdsourced reports (12 citizen submissions recorded)',
        'Classified as National Highway corridor with heavy freight movement',
      ],
      confidence: 0.93,
      explanation: 'Calculated prototype risk level HIGH based on high severity detection, 3 high-relevance news accident records, and high-speed corridor exposure.',
    },
    status: 'REPORTED',
    citizenReportCount: 12,
    createdAt: '2026-09-27T08:15:00Z',
    updatedAt: '2026-09-27T08:15:00Z',
    timeline: [
      {
        id: 'tl-1',
        status: 'REPORTED',
        title: 'Report Submitted by Citizen',
        comment: 'Citizen flagged dangerous road hazard with GPS verification and high-resolution photo.',
        timestamp: '2026-09-27T08:15:00Z',
        actor: 'Citizen #4029',
        actorRole: 'CITIZEN',
      },
      {
        id: 'tl-2',
        status: 'AI_ANALYZED',
        title: 'Hazard & Accident Intelligence Evaluated',
        comment: 'Groq Vision detected high-severity pothole. Public news archives matched 3 high-relevance incidents.',
        timestamp: '2026-09-27T08:15:15Z',
        actor: 'KIZUNA AI Pipeline',
        actorRole: 'SYSTEM_AI',
      },
      {
        id: 'tl-3',
        status: 'AUTHORITY_IDENTIFIED',
        title: 'Authority Routing Engine Executed',
        comment: 'Matched to NHAI PIU Raipur under National Highways jurisdiction rules.',
        timestamp: '2026-09-27T08:15:20Z',
        actor: 'Authority Routing Engine',
        actorRole: 'SYSTEM_AI',
      }
    ],
    isDemo: true,
  },
  {
    id: 'KZ-2026-00108',
    citizenId: 'citizen-demo-user-2',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
    location: {
      latitude: 21.2389,
      longitude: 81.6521,
      formattedAddress: 'Great Eastern Rd, Near Telibandha Lake Chowk, Raipur, Chhattisgarh 492001',
      locality: 'Telibandha',
      district: 'Raipur',
      state: 'Chhattisgarh',
      roadName: 'Great Eastern Road (GE Road)',
      roadPlaceId: 'ChIJ5b0S1vM3VToRzK_DemoRoad_02',
      roadCategory: 'municipal_road',
    },
    hazardAnalysis: {
      hazardType: 'damaged_divider',
      severity: 'critical',
      confidence: 0.96,
      description: 'Concrete median divider shattered with exposed rebar protruding into oncoming traffic lane. High risk of head-on crossover collisions.',
      requiresAttention: true,
      visibleRoadClues: ['Urban commercial corridor', 'Median concrete barrier', 'Pedestrian crossing marks'],
      additionalHazards: ['Exposed steel reinforcement rods', 'Fallen concrete blocks on fast lane'],
    },
    accidentIntelligence: {
      totalFound: 4,
      highRelevanceCount: 2,
      summary: '2 recorded pedestrian and vehicular accidents near Marine Drive / Telibandha Chowk.',
      events: [
        {
          id: 'acc-demo-5',
          date: '2026-02-14',
          location: 'Telibandha Chowk, GE Road',
          eventType: 'vehicle_accident',
          severity: 'serious',
          source: 'Nai Dunia',
          url: 'https://example.com/news/telibandha-divider-crash',
          title: 'Night car strikes unpainted damaged median divider at Telibandha',
          snippet: 'Vehicle sustained major front-end impact after crashing against unlit broken median separator.',
          relevance: 'HIGH',
          relevanceReason: 'Direct location match on GE Road Telibandha with divider hazard cited.',
        }
      ],
    },
    authorityRouting: {
      authorityId: 'auth-cg-rmc-urban',
      authorityName: 'Raipur Municipal Corporation (RMC)',
      department: 'Urban Infrastructure & Public Works Cell',
      jurisdiction: 'Raipur Urban Municipal Limits & Inner Arterial Roads',
      routingConfidence: 0.96,
      reason: 'Assigned because the identified road falls within Raipur municipal arterial network.',
      escalationAuthority: 'Urban Administration & Development Dept, Chhattisgarh',
      isDemo: true,
    },
    priorityAssessment: {
      priority: 'CRITICAL',
      factors: [
        'Critical severity: shattered median barrier with exposed rebar in urban traffic',
        'Direct collision history recorded on GE Road Telibandha section',
        'High pedestrian footfall and transit density near Telibandha Lake recreation zone',
      ],
      confidence: 0.95,
      explanation: 'Calculated prototype risk level CRITICAL due to severe median breach causing acute crossover collision risk.',
    },
    status: 'IN_PROGRESS',
    citizenReportCount: 18,
    createdAt: '2026-09-25T10:20:00Z',
    updatedAt: '2026-09-26T14:30:00Z',
    acknowledgedAt: '2026-09-25T11:05:00Z',
    assignedAt: '2026-09-25T14:00:00Z',
    assignedOfficer: {
      name: 'R. K. Sharma, Assistant Engineer (Roads)',
      badgeId: 'RMC-ENG-204',
      division: 'Central Zone II Infrastructure Wing',
    },
    timeline: [
      {
        id: 'tl-108-1',
        status: 'REPORTED',
        title: 'Case Created',
        comment: 'Citizen reported broken median barrier with high-risk obstruction.',
        timestamp: '2026-09-25T10:20:00Z',
        actor: 'Citizen #3812',
        actorRole: 'CITIZEN',
      },
      {
        id: 'tl-108-2',
        status: 'ACKNOWLEDGED',
        title: 'Authority Acknowledged',
        comment: 'RMC Zone Control acknowledged case within 45 minutes.',
        timestamp: '2026-09-25T11:05:00Z',
        actor: 'RMC Dispatch Desk',
        actorRole: 'AUTHORITY',
      },
      {
        id: 'tl-108-3',
        status: 'ASSIGNED',
        title: 'Officer Assigned',
        comment: 'Assigned to AE R. K. Sharma for immediate site barrier placement.',
        timestamp: '2026-09-25T14:00:00Z',
        actor: 'Executive Engineer RMC',
        actorRole: 'AUTHORITY',
      },
      {
        id: 'tl-108-4',
        status: 'IN_PROGRESS',
        title: 'Work In Progress',
        comment: 'Pre-cast concrete curb replacements delivered. Reflective retrofittings underway.',
        timestamp: '2026-09-26T14:30:00Z',
        actor: 'AE R. K. Sharma',
        actorRole: 'AUTHORITY',
      }
    ],
    isDemo: true,
  },
  {
    id: 'KZ-2026-00094',
    citizenId: 'citizen-demo-user-3',
    imageUrl: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=1200&q=80',
    location: {
      latitude: 21.2185,
      longitude: 81.5832,
      formattedAddress: 'VIP Road, Near Airport Corridor, Raipur, Chhattisgarh 492015',
      locality: 'Mana Camp',
      district: 'Raipur',
      state: 'Chhattisgarh',
      roadName: 'VIP Airport Road',
      roadPlaceId: 'ChIJ5b0S1vM3VToRzK_DemoRoad_03',
      roadCategory: 'state_highway',
    },
    hazardAnalysis: {
      hazardType: 'pothole',
      severity: 'medium',
      confidence: 0.92,
      description: 'Multiple surface depressions and top bituminous layer wear near curb boundary.',
      requiresAttention: true,
      visibleRoadClues: ['Boulevard median', 'Street lighting pole', 'Airport transit signage'],
      additionalHazards: ['Loose gravel chips scattering on motorcycle track'],
    },
    accidentIntelligence: {
      totalFound: 2,
      highRelevanceCount: 1,
      summary: '1 minor skidding incident involving a two-wheeler during rainy conditions.',
      events: [
        {
          id: 'acc-demo-6',
          date: '2025-09-11',
          location: 'VIP Road Airport turning',
          eventType: 'vehicle_accident',
          severity: 'minor',
          source: 'Daily Pioneer Raipur',
          url: 'https://example.com/news/vip-road-skid',
          title: 'Two-wheeler skids over loose gravel on VIP Road corridor',
          snippet: 'Rider treated for abrasions after skidding on loose bitumen gravel.',
          relevance: 'HIGH',
          relevanceReason: 'Location matches VIP road corridor and surface degradation.',
        }
      ],
    },
    authorityRouting: {
      authorityId: 'auth-cg-pwd-sh',
      authorityName: 'Chhattisgarh Public Works Department (CG PWD)',
      department: 'State Highways & Capital Project Division',
      jurisdiction: 'State Highways (SH-5, SH-9, SH-22) - Raipur Division',
      routingConfidence: 0.91,
      reason: 'Assigned to CG PWD State Highways & Capital project division for airport corridor maintenance.',
      escalationAuthority: 'Chief Engineer (State Highways), CG PWD',
      isDemo: true,
    },
    priorityAssessment: {
      priority: 'MEDIUM',
      factors: [
        'Moderate severity: bituminous layer wear with loose gravel',
        'One historical skidding incident on VIP road',
        'High VIP and transit visibility corridor requiring timely resurfacing',
      ],
      confidence: 0.88,
      explanation: 'Calculated prototype risk level MEDIUM based on surface wear and two-wheeler skidding risk.',
    },
    status: 'RESOLVED',
    citizenReportCount: 4,
    createdAt: '2026-09-20T09:00:00Z',
    updatedAt: '2026-09-24T16:00:00Z',
    acknowledgedAt: '2026-09-20T10:15:00Z',
    assignedAt: '2026-09-21T09:30:00Z',
    resolvedAt: '2026-09-24T16:00:00Z',
    assignedOfficer: {
      name: 'V. P. Agrawal, Sub-Divisional Officer',
      badgeId: 'PWD-CG-882',
      division: 'Capital Road Division I',
    },
    resolutionNotes: 'Cold mix patch repair and roller compaction completed over 45 square meters. Sweeper vehicle cleared loose aggregates.',
    resolutionEvidence: {
      afterImageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1200&q=80',
      notes: 'Completed cold asphalt milling and patch leveling with seamless grade matching.',
      verification: {
        hazardBefore: 'Surface depressions and aggregate chipping on curb lane',
        hazardVisibleAfter: false,
        visualResolutionConfidence: 0.94,
        explanation: 'The previously reported surface depression and loose gravel are no longer visible in the submitted post-repair photograph. Smooth asphalt patch visible.',
        verifiedAt: '2026-09-24T16:05:00Z',
        afterImageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1200&q=80',
      },
    },
    timeline: [
      {
        id: 'tl-94-1',
        status: 'REPORTED',
        title: 'Report Filed',
        comment: 'Citizen submitted report with photo evidence.',
        timestamp: '2026-09-20T09:00:00Z',
        actor: 'Citizen #2910',
        actorRole: 'CITIZEN',
      },
      {
        id: 'tl-94-2',
        status: 'ACKNOWLEDGED',
        title: 'Acknowledged by PWD',
        comment: 'Case logged into Capital Works docket.',
        timestamp: '2026-09-20T10:15:00Z',
        actor: 'PWD Raipur Control',
        actorRole: 'AUTHORITY',
      },
      {
        id: 'tl-94-3',
        status: 'IN_PROGRESS',
        title: 'Paving Crew Dispatched',
        comment: 'Cold-mix mobile repair unit deployed to site.',
        timestamp: '2026-09-23T11:00:00Z',
        actor: 'SDO V. P. Agrawal',
        actorRole: 'AUTHORITY',
      },
      {
        id: 'tl-94-4',
        status: 'RESOLVED',
        title: 'Resolved & AI-Verified',
        comment: 'Repair completed. Post-repair photograph submitted and validated by AI-assisted visual verification.',
        timestamp: '2026-09-24T16:00:00Z',
        actor: 'SDO V. P. Agrawal',
        actorRole: 'AUTHORITY',
      }
    ],
    isDemo: true,
  }
];

export const DEMO_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-1',
    userId: 'officer-nhai-01',
    userRole: 'authority',
    caseId: 'KZ-DEMO-001',
    title: 'New High-Priority Case Assigned',
    message: 'High-severity pothole hazard on NH-30 Tatibandh assigned to your division with 7 accident records.',
    read: false,
    createdAt: '2026-09-27T08:15:20Z',
    type: 'CASE_ASSIGNED',
  },
  {
    id: 'notif-2',
    userId: 'citizen-demo-user',
    userRole: 'citizen',
    caseId: 'KZ-DEMO-001',
    title: 'Report Forwarded to NHAI PIU Raipur',
    message: 'Your report KZ-DEMO-001 has been analyzed and routed to National Highways Authority of India for action.',
    read: false,
    createdAt: '2026-09-27T08:15:25Z',
    type: 'CASE_ASSIGNED',
  },
  {
    id: 'notif-3',
    userId: 'officer-rmc-01',
    userRole: 'authority',
    caseId: 'KZ-2026-00108',
    title: 'Critical Divider Hazard Update',
    message: 'Work order executed for broken median barrier on GE Road Telibandha Chowk.',
    read: true,
    createdAt: '2026-09-26T14:30:00Z',
    type: 'STATUS_CHANGED',
  },
  {
    id: 'notif-4',
    userId: 'citizen-demo-user-3',
    userRole: 'citizen',
    caseId: 'KZ-2026-00094',
    title: 'Hazard Resolved & Verified',
    message: 'Your reported road issue on VIP Airport Road has been repaired and verified by authority engineers.',
    read: true,
    createdAt: '2026-09-24T16:05:00Z',
    type: 'RESOLVED',
  }
];
